# Kmeans

Algorithm
1. assign centroids (start with random)
2. Assign points to closest centroid
3. find new centroid
4. Measure sum of squares

based on: https://gist.github.com/ImadDabbura/6e2230b33373991aa3ccdbff6ebb3fd7#file-kmeans-py
"""


In [1]:
%pip install -U numpy

You should consider upgrading via the '/usr/local/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy.typing as npt
import numpy as np
from sklearn.datasets import make_blobs

In [3]:
class Kmeans:
    def __init__(self, max_iter=100, n_clusters=3, random_state=0, n_init=3):
        self.n_clusters = n_clusters
        self.random_state = random_state
        self.max_iter = max_iter
        self.n_init

    def _initialize_centroids(self, X):
        np.random.RandomState(self.random_state)
        random_idx = np.random.permutation(X.shape[0])
        return X[random_idx[:self.n_clusters]]

    def _calculate_centroids(self, X, labels):
        """Given points with labels, calculate their centroids

        calculate means of all points with a label
        this comes after the initialization part that makes initial
        labels

        Use axis=0 because at the end we want a vector of means from 
        each dimensions.
        """

        centroids = np.zeros((self.n_clusters, X.shape[1]))
        for i in range(self.n_clusters):
            centroids[i, :] = np.mean(X[labels == i], axis=0)
        return centroids
    
    def _calculate_distance(self, X, centroids):
        """keep track distance from point to each cluster
        axis 0 is the index of the point
        axis 1 is the index of the cluster
        value at i j is the distance for point i to cluster j (in indices)
        """
        self.distances = np.zeros((X.shape[0], self.n_clusters))
        for i in range(self.n_clusters):
            self.distances[:, i] = np.linalg.norm(X-centroids[i, :], axis=1)
        return self.distances

    def _find_closest_cluster(self, distance):
        return np.argmin(distance, axis=1)

    def _update_centroids(self, X, centroids) -> None:
        dist = self._calculate_distance(X, self.centroids)
        labels = self._find_closest_cluster(dist)
        centroids = self._calculate_centroids(X, labels)
        return centroids

    def _check_stopping_criterion(self, old_centroids, new_centroids):
        return np.all(old_centroids == new_centroids)

    def _compute_sse(self, X, labels):
        distance = np.zeros(X.shape[0])
        for i in range(self.n_clusters):
            distance[labels == i] = np.linalg.norm(X[labels == i] - centroids[i], axis=1)
        return np.sum(np.square(distance))

    def fit(self, X: npt.ArrayLike):
        self.centroids = self._initialize_centroids(X)
        for i in range(self.max_iter):
            new_centroids = self._one_iteration(X, self.centroids)
            if self._check_stopping_criterion(self.centroids, new_centroids):
                break
            self.centroids = new_centroids
        self._error = self._compute_sse(X, self.centroids, self.labels)
    
    def predict(self):
        distance = self._calculate_distance(X, self.centroids)
        return self._find_closest_cluster(distance)

# Test components

In [4]:
from sklearn.datasets import make_blobs
X, y = make_blobs(n_samples=20, n_features=2, centers=3)

In [5]:
# X = np.array([[1, 2], [1, 4], [1, 0],
#               [10, 2], [10, 4], [10, 0]])

In [6]:
z = np.zeros((X.shape[0], X.shape[1]))

In [7]:
X

array([[-4.02157399, -4.27182757],
       [ 9.73784983, -5.44347372],
       [ 6.6659809 ,  7.73895312],
       [ 5.09475379,  5.90738894],
       [ 5.55388887,  4.87645956],
       [-2.3975107 , -4.60187683],
       [ 6.1893496 , -6.73422976],
       [-6.01056483, -3.22049543],
       [ 9.90440172, -6.87822665],
       [-4.37145615, -3.6390868 ],
       [ 6.5021206 ,  6.39319468],
       [ 9.34906702, -5.18148381],
       [ 8.66005985, -5.32405394],
       [ 9.37231893, -3.56609504],
       [-2.2017369 , -4.90793962],
       [ 6.10489939,  5.44743885],
       [-1.75931783, -2.46488367],
       [ 5.52186383,  6.07203095],
       [-2.75791124, -1.52743823],
       [ 9.22521423, -4.57585465]])

In [8]:
y

array([0, 1, 2, 2, 2, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 2, 0, 2, 0, 1])

In [9]:
# use the index that changes is the 1st axis
a = np.linalg.norm(X, axis=1)
print(a)

# use the index that changes is the 0th axis
b = np.linalg.norm(X, axis=0)
print(b)

# Treats every value in the np.array as a vector
c = np.linalg.norm(X) # defaults to axis=-1
print(c)

[ 5.8669897  11.15603538 10.21404409  7.80088202  7.39090924  5.18896212
  9.14646921  6.81897943 12.05848976  5.68793298  9.11869017 10.68891148
 10.16573593 10.02783107  5.37917435  8.18195494  3.02834125  8.20734671
  3.15264047 10.29771933]
[29.5052533  23.07948361]
37.45961206050517


## Compute centroids

In [10]:
np.random.RandomState(0)
idxs = np.random.permutation(X.shape[0])[:3]
n_clusters = 3
centroids = X[idxs]
print(centroids)

[[ 8.66005985 -5.32405394]
 [ 6.10489939  5.44743885]
 [-2.3975107  -4.60187683]]


In [11]:
distances = np.zeros((X.shape[0], n_clusters))
for i in range(centroids.shape[0]):
    distances[:,i] = np.linalg.norm(X - centroids[i,:], axis=1)

In [12]:
distances

array([[12.72521187, 14.03601093,  1.65726102],
       [ 1.08438569, 11.48086693, 12.16450823],
       [13.21432951,  2.3592054 , 15.31153042],
       [11.78374799,  1.10993164, 12.90653688],
       [10.66296271,  0.79349225, 12.37188813],
       [11.08112838, 13.16357562,  0.        ],
       [ 2.84482073, 12.18196134,  8.84766064],
       [14.82066756, 14.8968976 ,  3.86812289],
       [ 1.99093935, 12.89799396, 12.51074808],
       [13.13999709, 13.86791166,  2.19622979],
       [11.91430305,  1.0257869 , 14.14549521],
       [ 0.70360296, 11.11299332, 11.76086869],
       [ 0.        , 11.07040659, 11.08112838],
       [ 1.89676896,  9.58748266, 11.81531774],
       [10.86976448, 13.27531807,  0.36332053],
       [11.07040659,  0.        , 13.16357562],
       [10.80454932, 11.1557501 ,  2.23025333],
       [11.82028025,  0.85442715, 13.29092925],
       [12.03263707, 11.27822338,  3.09549048],
       [ 0.93765754, 10.49775106, 11.62275406]])

In [13]:
# assign point indices to centroid
points_to_centroids = np.argmin(distances, axis=1)
new_centroids = np.zeros((centroids.shape[0], centroids.shape[1]))
#calcultate new centroids
for i in range(n_clusters):
    new_centroids[i,:] = np.mean(X[points_to_centroids == i], axis = 0)

In [14]:
centroids

array([[ 8.66005985, -5.32405394],
       [ 6.10489939,  5.44743885],
       [-2.3975107 , -4.60187683]])

In [15]:
new_centroids

array([[ 8.9197516 , -5.38620251],
       [ 5.90725123,  6.07257768],
       [-3.36001023, -3.51907831]])

In [16]:
points_to_centroids

array([2, 0, 1, 1, 1, 2, 0, 2, 0, 2, 1, 0, 0, 0, 2, 1, 2, 1, 2, 0])

In [73]:
X[points_to_centroids == 0]

array([[ 3.79074203,  8.15207942],
       [ 3.83502883,  9.00940876],
       [ 8.52225541,  2.07436062],
       [ 8.26827564,  2.47078827],
       [ 3.81603864, 11.07256391],
       [ 6.49861228,  9.98923315],
       [ 3.58542397,  9.19161513],
       [ 6.08596313, 10.04060336],
       [ 3.89785137,  9.18125094]])

In [17]:
n_clusters = 3

In [18]:
d = np.zeros((X.shape[0], n_clusters))

In [19]:
centroids = np.zeros((X.shape[0]))

In [20]:
X

array([[-4.02157399, -4.27182757],
       [ 9.73784983, -5.44347372],
       [ 6.6659809 ,  7.73895312],
       [ 5.09475379,  5.90738894],
       [ 5.55388887,  4.87645956],
       [-2.3975107 , -4.60187683],
       [ 6.1893496 , -6.73422976],
       [-6.01056483, -3.22049543],
       [ 9.90440172, -6.87822665],
       [-4.37145615, -3.6390868 ],
       [ 6.5021206 ,  6.39319468],
       [ 9.34906702, -5.18148381],
       [ 8.66005985, -5.32405394],
       [ 9.37231893, -3.56609504],
       [-2.2017369 , -4.90793962],
       [ 6.10489939,  5.44743885],
       [-1.75931783, -2.46488367],
       [ 5.52186383,  6.07203095],
       [-2.75791124, -1.52743823],
       [ 9.22521423, -4.57585465]])

In [21]:
X - np.array([0, 1])

array([[-4.02157399, -5.27182757],
       [ 9.73784983, -6.44347372],
       [ 6.6659809 ,  6.73895312],
       [ 5.09475379,  4.90738894],
       [ 5.55388887,  3.87645956],
       [-2.3975107 , -5.60187683],
       [ 6.1893496 , -7.73422976],
       [-6.01056483, -4.22049543],
       [ 9.90440172, -7.87822665],
       [-4.37145615, -4.6390868 ],
       [ 6.5021206 ,  5.39319468],
       [ 9.34906702, -6.18148381],
       [ 8.66005985, -6.32405394],
       [ 9.37231893, -4.56609504],
       [-2.2017369 , -5.90793962],
       [ 6.10489939,  4.44743885],
       [-1.75931783, -3.46488367],
       [ 5.52186383,  5.07203095],
       [-2.75791124, -2.52743823],
       [ 9.22521423, -5.57585465]])

In [22]:
np.linalg.norm(X, axis=0)

array([29.5052533 , 23.07948361])

In [23]:
np.linalg.norm(X, axis=-1)

array([ 5.8669897 , 11.15603538, 10.21404409,  7.80088202,  7.39090924,
        5.18896212,  9.14646921,  6.81897943, 12.05848976,  5.68793298,
        9.11869017, 10.68891148, 10.16573593, 10.02783107,  5.37917435,
        8.18195494,  3.02834125,  8.20734671,  3.15264047, 10.29771933])

In [24]:
np.linalg.norm([1, 2])

2.23606797749979

In [25]:
indices = np.random.permutation(X.shape[0])[:3]
X[indices]

array([[ 9.22521423, -4.57585465],
       [ 6.6659809 ,  7.73895312],
       [ 9.34906702, -5.18148381]])

In [26]:
n_clusters = 3
centroids = np.zeros([n_clusters, X.shape[1]])

In [27]:
centroids = np.zeros([n_clusters, X.shape[1]])
for i in range(n_clusters):
    centroids[i, :] = np.mean(X[y==i,:])

In [28]:
centroids

array([[-3.43954427, -3.43954427],
       [ 1.76677454,  1.76677454],
       [ 5.98991446,  5.98991446]])

In [29]:
for k in range(3):
    row_norm = np.linalg.norm(X - centroids[k,:], axis = 1)

In [30]:
centroids[k,:]

array([5.98991446, 5.98991446])

In [31]:
X - centroids[k,:]

array([[-10.01148844, -10.26174203],
       [  3.74793537, -11.43338817],
       [  0.67606644,   1.74903867],
       [ -0.89516067,  -0.08252551],
       [ -0.43602558,  -1.1134549 ],
       [ -8.38742515, -10.59179129],
       [  0.19943514, -12.72414422],
       [-12.00047929,  -9.21040989],
       [  3.91448726, -12.86814111],
       [-10.3613706 ,  -9.62900125],
       [  0.51220614,   0.40328022],
       [  3.35915257, -11.17139827],
       [  2.6701454 , -11.3139684 ],
       [  3.38240447,  -9.5560095 ],
       [ -8.19165136, -10.89785408],
       [  0.11498494,  -0.54247561],
       [ -7.74923229,  -8.45479812],
       [ -0.46805063,   0.08211649],
       [ -8.7478257 ,  -7.51735268],
       [  3.23529977, -10.56576911]])

In [32]:
centroids

array([[-3.43954427, -3.43954427],
       [ 1.76677454,  1.76677454],
       [ 5.98991446,  5.98991446]])

In [33]:
centroids[1,:]

array([1.76677454, 1.76677454])

In [34]:
np.mean(X[y == 1] - centroids[1])

6.344131569286608e-17

In [35]:
centroids = np.zeros([n_clusters, X.shape[1]])
for i in range(n_clusters):
    centroids[i, :] = np.mean(X[y==i,:])

In [36]:
distances = np.zeros([X.shape[0], n_clusters])
distances

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
for i in range(n_clusters):
    row_norm = np.linalg.norm(X-centroids[i, :], axis=1)
    print(row_norm)
    distances[:, i] = np.square(row_norm)

[ 1.01560528 13.32889525 15.06918853 12.65699031 12.24899014  1.56104162
 10.17696171  2.58033508 13.77989228  0.95303566 13.98282717 12.90670106
 12.24548066 12.8124882   1.92050826 13.04127577  1.94245313 13.06816354
  2.02996874 12.71563247]
[ 8.36478895 10.74828922  7.72458024  5.31226256  4.90024243  7.60927013
  9.58260112  9.23904051 11.87253224  8.17931616  6.62021643 10.28442772
  9.88924825  9.28890755  7.76536491  5.68916663  5.50819922  5.71278639
  5.59684011  9.79067248]
[14.33643088 12.03201499  1.87515388  0.89895667  1.19578431 13.51054934
 12.72570707 15.12756271 13.45036305 14.14481057  0.65191262 11.66550664
 11.62478204 10.13696097 13.6332819   0.55452801 11.46883658  0.47519944
 11.53408192 11.0500064 ]


In [38]:
X-centroids[i, :]

array([[-10.01148844, -10.26174203],
       [  3.74793537, -11.43338817],
       [  0.67606644,   1.74903867],
       [ -0.89516067,  -0.08252551],
       [ -0.43602558,  -1.1134549 ],
       [ -8.38742515, -10.59179129],
       [  0.19943514, -12.72414422],
       [-12.00047929,  -9.21040989],
       [  3.91448726, -12.86814111],
       [-10.3613706 ,  -9.62900125],
       [  0.51220614,   0.40328022],
       [  3.35915257, -11.17139827],
       [  2.6701454 , -11.3139684 ],
       [  3.38240447,  -9.5560095 ],
       [ -8.19165136, -10.89785408],
       [  0.11498494,  -0.54247561],
       [ -7.74923229,  -8.45479812],
       [ -0.46805063,   0.08211649],
       [ -8.7478257 ,  -7.51735268],
       [  3.23529977, -10.56576911]])

In [39]:
distances

array([[1.03145408e+00, 6.99696942e+01, 2.05533250e+02],
       [1.77659448e+02, 1.15525721e+02, 1.44769385e+02],
       [2.27080443e+02, 5.96691399e+01, 3.51620209e+00],
       [1.60199404e+02, 2.82201335e+01, 8.08123087e-01],
       [1.50037759e+02, 2.40123758e+01, 1.42990012e+00],
       [2.43685095e+00, 5.79009919e+01, 1.82534943e+02],
       [1.03570550e+02, 9.18262443e+01, 1.61943620e+02],
       [6.65812910e+00, 8.53598695e+01, 2.28843153e+02],
       [1.89885431e+02, 1.40957022e+02, 1.80912266e+02],
       [9.08276966e-01, 6.69012128e+01, 2.00075666e+02],
       [1.95519456e+02, 4.38272655e+01, 4.24990067e-01],
       [1.66582932e+02, 1.05769453e+02, 1.36084045e+02],
       [1.49951797e+02, 9.77972310e+01, 1.35135557e+02],
       [1.64159854e+02, 8.62838035e+01, 1.02757978e+02],
       [3.68835199e+00, 6.03008922e+01, 1.85866375e+02],
       [1.70074874e+02, 3.23666170e+01, 3.07501318e-01],
       [3.77312417e+00, 3.03402586e+01, 1.31534212e+02],
       [1.70776898e+02, 3.26359